// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_of_your_choice;

#nullable disable

namespace api_of_your_choice.Migrations
{
    [DbContext(typeof(FlyrodContext))]
    [Migration("20220927233026_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_of_your_choice.Models.Flyrod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Construction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LengthFeet")
                        .HasColumnType("float");

                    b.Property<string>("LineWeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sections")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearMade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flyrod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Construction = "Hex",
                            LengthFeet = 6.0,
                            LineWeight = "WF4",
                            Maker = "Leonard",
                            Model = "37H",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1959
                        },
                        new
                        {
                            Id = 2,
                            Construction = "Hex",
                            LengthFeet = 7.0,
                            LineWeight = "DT4",
                            Maker = "Payne",
                            Model = "98",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1962
                        },
                        new
                        {
                            Id = 3,
                            Construction = "Hex",
                            LengthFeet = 7.5,
                            LineWeight = "DT5",
                            Maker = "Orvis",
                            Model = "Far and Fine",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1972
                        },
                        new
                        {
                            Id = 4,
                            Construction = "Penta",
                            LengthFeet = 7.5,
                            LineWeight = "DT5",
                            Maker = "Uslan",
                            Model = "7513",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1955
                        },
                        new
                        {
                            Id = 5,
                            Construction = "Hex",
                            LengthFeet = 8.5,
                            LineWeight = "WF6",
                            Maker = "EC Powell",
                            Model = "B9",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1946
                        },
                        new
                        {
                            Id = 6,
                            Construction = "Quad",
                            LengthFeet = 7.5,
                            LineWeight = "WF6",
                            Maker = "WE Edwards",
                            Model = "37",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1950
                        },
                        new
                        {
                            Id = 7,
                            Construction = "Hex",
                            LengthFeet = 8.5,
                            LineWeight = "DT7",
                            Maker = "Browning",
                            Model = "Silaflex",
                            Sections = 2,
                            Type = "Bamboo",
                            YearMade = 1975
                        },
                        new
                        {
                            Id = 8,
                            Construction = "Tubular",
                            LengthFeet = 8.0,
                            LineWeight = "WF6",
                            Maker = "Fenwick",
                            Model = "FF80",
                            Sections = 2,
                            Type = "Fiberglass",
                            YearMade = 1977
                        },
                        new
                        {
                            Id = 9,
                            Construction = "Tubular",
                            LengthFeet = 8.0,
                            LineWeight = "WF4",
                            Maker = "Winston",
                            Model = "Stalker",
                            Sections = 2,
                            Type = "Fiberglass",
                            YearMade = 1979
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
